{
 "title": "EnergyManagementDemoImport",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": " 1s",
 "panels": [
  {
   "title": "Price",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Price (cents/kWh)" }
   ],
   "targets": [
    {
     "alias": "price (cents/kWh)",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sensor",
     "query": "SELECT mean(\"price (cents/kWh)\") FROM \"sensor\" WHERE $timeFilter GROUP BY time(1h) fill(none)",
     "select": [
      [
       { "params": [ "price (cents/kWh)" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cost (ESS MPC)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "case" ], "type": "tag" }
     ],
     "measurement": "result",
     "select": [
      [
       { "params": [ "cost ($)" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "case", "operator": "=", "value": "ESS_MPC" }
     ]
    }
   ]
  },
  {
   "title": "Cost (ESS RLRA)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "case" ], "type": "tag" }
     ],
     "measurement": "result",
     "select": [
      [
       { "params": [ "cost ($)" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "case", "operator": "=", "value": "ESS_RLRA" }
     ]
    }
   ]
  },
  {
   "title": "Cost (ESS RLRS)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "case" ], "type": "tag" }
     ],
     "measurement": "result",
     "select": [
      [
       { "params": [ "cost ($)" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "case", "operator": "=", "value": "ESS_RLRS" }
     ]
    }
   ]
  },
  {
   "title": "Cost (Without ESS)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "case" ], "type": "tag" }
     ],
     "measurement": "result",
     "select": [
      [
       { "params": [ "cost ($)" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "case", "operator": "=", "value": "WOESS" }
     ]
    }
   ]
  },
  {
   "title": "ESS SOC (MPC)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 3 },
   "targets": [
    {
     "measurement": "result",
     "query": "SELECT mean(\"SOC\") FROM \"result\" WHERE (\"case\" = 'ESS_RLRA') AND $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "soc" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "case", "operator": "=", "value": "ESS_MPC" }
     ]
    }
   ]
  },
  {
   "title": "ESS SOC (RLRA)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 3 },
   "targets": [
    {
     "measurement": "result",
     "query": "SELECT mean(\"SOC\") FROM \"result\" WHERE (\"case\" = 'ESS_RLRA') AND $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "soc" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "case", "operator": "=", "value": "ESS_RLRA" }
     ]
    }
   ]
  },
  {
   "title": "ESS SOC (RLRA)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 3 },
   "targets": [
    {
     "measurement": "result",
     "query": "SELECT mean(\"SOC\") FROM \"result\" WHERE (\"case\" = 'ESS_RLRA') AND $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "soc" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "case", "operator": "=", "value": "ESS_RLRA" }
     ]
    }
   ]
  },
  {
   "title": "Load & Solar",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Power (kW)" }
   ],
   "targets": [
    {
     "alias": "load (kW)",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sensor",
     "query": "SELECT mean(\"value\") FROM \"power\" WHERE (\"uuid\" = '0CEFAFCC8B2D') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Load (kWh)" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PV (kW)",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sensor",
     "query": "SELECT mean(\"value\") FROM \"power\" WHERE (\"uuid\" = '0CEFAFCC8B2D') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PV (kWh)" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ESS Action",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "MPC",
     "measurement": "result",
     "select": [
      [
       { "params": [ "action" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "case", "operator": "=", "value": "ESS_MPC" }
     ]
    },
    {
     "alias": "RLRA",
     "measurement": "result",
     "select": [
      [
       { "params": [ "action" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "case", "operator": "=", "value": "ESS_RLRA" }
     ]
    },
    {
     "alias": "RLRS",
     "measurement": "result",
     "select": [
      [
       { "params": [ "action" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "case", "operator": "=", "value": "ESS_RLRS" }
     ]
    }
   ]
  }
 ]
}